export const GET_MOVIE_SHOWTIME_REQUEST = "GET_MOVIE_SHOWTIME_REQUEST";
export const GET_MOVIE_SHOWTIME_SUCCESS = "GET_MOVIE_SHOWTIME_SUCCESS";
export const GET_MOVIE_SHOWTIME_FAIL = "GET_MOVIE_SHOWTIME_FAIL";
export const RESET_MOVIEDETAIL_REDUCER = "RESET_MOVIEDETAIL_REDUCER";
