export const GET_THEATER_BRANCHES_SHOWTIME_REQUEST =
  "GET_THEATER_BRANCHES_SHOWTIME_REQUEST";
export const GET_THEATER_BRANCHES_SHOWTIME_SUCCESS =
  "GET_THEATER_BRANCHES_SHOWTIME_SUCCESS";
export const GET_THEATER_BRANCHES_SHOWTIME_FAIL =
  "GET_THEATER_BRANCHES_SHOWTIME_FAIL";
export const GET_MOVIE_SHOWTIME_REQUEST = "GET_MOVIE_SHOWTIME_REQUEST";
export const GET_MOVIE_SHOWTIME_SUCCESS = "GET_MOVIE_SHOWTIME_SUCCESS";
export const GET_MOVIE_SHOWTIME_FAIL = "GET_MOVIE_SHOWTIME_FAIL";
export const GET_THEATER_BRANCHES_SHOWTIME_REQUEST2 =
  "GET_THEATER_BRANCHES_SHOWTIME_REQUEST2";
export const GET_THEATER_BRANCHES_SHOWTIME_SUCCESS2 =
  "GET_THEATER_BRANCHES_SHOWTIME_SUCCESS2";
export const GET_THEATER_BRANCHES_SHOWTIME_FAIL2 =
  "GET_THEATERS_SHOWTIME_FAIL2";
